[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; =============================
; OTA upload
; =============================
upload_protocol = espota
upload_port = stanok.local
upload_flags =
    --auth=ota123
 
; =============================
; Filesystem
; =============================
board_build.filesystem = littlefs
board_build.partitions = partitions.csv

; =============================
; Libraries (GitHub URLs)
; =============================
lib_deps = 
    https://github.com/tzapu/WiFiManager.git
    https://github.com/ESP32Async/AsyncTCP.git
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    https://github.com/bblanchon/ArduinoJson.git

    https://github.com/adafruit/Adafruit-GFX-Library.git
    https://github.com/adafruit/Adafruit_SSD1306.git
    https://github.com/madhephaestus/ESP32Servo.git

; =============================
; Build Optimizations
; =============================
build_flags = 
    -O2                    # Makes code smaller and faster
    -ffunction-sections    # Removes unused functions
    -fdata-sections        # Removes unused data
    -Wl,--gc-sections      # Links only used code
    -D CORE_DEBUG_LEVEL=0  # Reduces debug output

monitor_filters = esp32_exception_decoder